# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BuKzAsJ_kOjSSK9SBSyz-dQubqomwdeD
"""

from tkinter import *
from tkinter import ttk
from tkinter import filedialog
import os
from PIL import Image

selected_image_path = ""
diag = 15

def get_folder():
    filepath = filedialog.askdirectory()
    folder_path.delete(0, END)
    folder_path.insert(INSERT, filepath)
    tree.delete(*tree.get_children())
    scan(filepath)

def image_info(image_path):
    img = Image.open(image_path)
    name = os.path.basename(image_path)
    width, height = img.size
    resolution = (width**2 + height**2)**(1/2) / diag
    depth = img.mode
    compression = img.info.get("compression", "N/A")
    entropy = '%.3f'%img.entropy()

    return name, str(width) + 'x' + str(height), resolution, depth, compression, entropy

def scan(folder_path):
    for root, dirs, files in os.walk(folder_path):
        for file in files:
            if file.endswith(('.jpg', '.gif', '.tif', '.bmp', '.png', '.pcx')):
                tree.insert("", END, values=image_info(os.path.join(root, file)))

def show_image(event):
    global selected_image_path
    selected_item = tree.item(tree.selection())
    image_name = selected_item['values'][0]
    selected_image_path = os.path.join(folder_path.get(), image_name)
    img = Image.open(selected_image_path)
    img.show()


root = Tk()
root.iconbitmap(default="icon.ico")
root.title("Image Info")
root.geometry('600x650')
root.configure(bg='#FF69B4')

folder_path = Entry(root, width=50, bg='lightblue', font=('Arial', 12, 'bold'), foreground='#FF69B4')
folder_path.grid(row=0, column=0, padx=20, pady=20, sticky=(W, E))
btn_folder_path = Button(root, text="Choose Folder", command=get_folder, width=20, bg='lightblue', font=('Arial', 12, 'bold'), foreground='#FF69B4')
btn_folder_path.grid(row=0, column=1, padx=20, pady=20, sticky=(W, E))

columns = ('Name', 'Size', 'Dots/Inch', 'Color Depth', 'Compression', "Entropy")
tree = ttk.Treeview(root, columns=columns, show="headings")
tree.grid(row=1, columnspan=2, sticky=(N, S, W, E))

style = ttk.Style()
style.theme_use("default")
style.configure("Treeview", font=('Arial', 12), rowheight=25, background='lightblue', foreground='#FF69B4')
style.configure("Treeview.Heading", font=('Arial', 12, 'bold'), background='lightblue', foreground='#FF69B4')

tree.heading("Name", text="Name")
tree.heading("Size", text="Size")
tree.heading("Dots/Inch", text="Dots/Inch")
tree.heading("Color Depth", text="Color Depth")
tree.heading("Compression", text="Compression")
tree.heading("Entropy", text="Entropy")

tree.column("#1", stretch=YES, width=100)
tree.column("#2", stretch=YES, width=100)
tree.column("#3", stretch=YES, width=100)
tree.column("#4", stretch=YES, width=100)
tree.column("#5", stretch=YES, width=100)
tree.column("#6", stretch=YES, width=100)

scrollbar = ttk.Scrollbar(root, orient=VERTICAL, command=tree.yview)
tree.configure(yscroll=scrollbar.set)
scrollbar.grid(row=1, column=2, sticky=(N, S, W, E))

tree.bind("<<TreeviewSelect>>", show_image)

root.grid_rowconfigure(1, weight=1)
root.grid_columnconfigure(0, weight=1)
root.grid_columnconfigure(1, weight=1)

root.mainloop()